dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: LgW8B1qDOcuiRrcuP0aahX1odatQ+v6hRhBY820viBwEJS54zKgQi74KSKSJnQe0U258ODh3WZqjK0r9EZ3CsgFvkKtZFT033LXeYb4930gOIWLJAh1J7tsB8bZRfcfzA9g9vT6uq8urIJaFNUGI/lBTFqvTVaspCV6h2FivWDgEAbezwGrGZgomZqjrC9w4lTd2KINO50icuYAHtwafZpHQFDHkvSd00qewIK0IZ0wN0wKVVLZ+FLjab+98RU11ygM6IkwdlXakzIuRyJURqX7I2deKBMLQJ2hXaMyEd4Jo7m4zifDUVuloPfiPaIDawsvP0W4uM5QbqsOvBpb6/04bmjTrK1mmtFqKTZqfTVwPEBsibU0bquM2zb1qXGYCJljQvA/4GFJzD6wMsQYvuO96F8ux7PvbrN1najyZfC9Zu+mUMz03uMxZ1uL+BvuUXWG8mOfGZZ6PDGVALvDef8gqfxi58Gz33qBsK8xfA/SUVeenHfxXxw5WCoVtAfF8rBBSr6P59llcIykZLn281C1w9670GJUjNmN1xtBgLaKKZ+W5/wUH4fX5X2tFHJ+3c6Pct+sqw+bJED6nuS8MrcdkZpCYLsrDgxsVpsBu32YRZC7IJ1kmQ0kToZvNj1Tlyigb3Ca5ZchVC2pOd3rkjT2mGpeNU41rgsejPAbbsA0=
